"""add accepted_privacy to user

Revision ID: 85b34e0cbb92
Revises: e47d5be45f37
Create Date: 2026-05-06 16:00:58.129374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b34e0cbb92'
down_revision = 'e47d5be45f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_privacy', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accepted_privacy')

    # ### end Alembic commands ###
